<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Especies_pla extends Public_Controller{
    function __construct()
    {
        parent::__construct();
        /* CARGA LA BASE DE DATOS O MODELO*/
        $this->load->model('common/Especies_model');
        if (!$this->ion_auth->logged_in() )
        {
            redirect('auth/login', 'refresh');
        }
        else
        {
            $this->data['user_login']  = $this->prefs_model->user_info_login($this->ion_auth->user()->row()->id);
        }

    }


    /*
     INDEX, LISTAR LAS ESPECIES
     */
        public function index()
        {
            if ( ! $this->ion_auth->logged_in())
            {
                redirect('auth/login', 'refresh');
            }
            else
            {
                /* CARGO EL LISTADO DE especies*/
                $this->data['especies'] = $this->Especies_model->get_all_especies();


                /* Load Template */
                $this->template->user_render('public/especies/index', $this->data);
            }
        }

    /*
     CREAR UNA NUEVA ESPECIE
     */
    function crear()
    {   
        if ( ! $this->ion_auth->logged_in())
        {
            redirect('auth/login', 'refresh');
        }
        else
        {
            $this->load->library('form_validation');

    		$this->form_validation->set_rules('nombreEspecie','NombreEspecie','required|max_length[50]|min_length[4]');
    		$this->form_validation->set_rules('nombreCientificoEspecie','NombreCientificoEspecie','required|max_length[50]|min_length[4]');
    		$this->form_validation->set_rules('descripcionCuidados','DescripcionCuidados','max_length[255]|required|min_length[4]');
    		$this->form_validation->set_rules('luzMax','LuzMax','required|is_natural');
    		$this->form_validation->set_rules('luzMin','LuzMin','required|is_natural');
    		$this->form_validation->set_rules('humedadMax','HumedadMax','required|is_natural');
    		$this->form_validation->set_rules('humedadMin','HumedadMin','required|is_natural');
    		$this->form_validation->set_rules('temperaturaMax','TemperaturaMax','required|is_natural');
    		$this->form_validation->set_rules('temperaturaMin','TemperaturaMin','is_natural|required');
    		$this->form_validation->set_rules('descripcionSustrato','DescripcionSustrato','max_length[255]');
    		
    		if($this->form_validation->run())     
            {   
                $params = array(
    				'nombreEspecie' => $this->input->post('nombreEspecie'),
    				'nombreCientificoEspecie' => $this->input->post('nombreCientificoEspecie'),
    				'luzMax' => $this->input->post('luzMax'),
    				'luzMin' => $this->input->post('luzMin'),
    				'humedadMax' => $this->input->post('humedadMax'),
    				'humedadMin' => $this->input->post('humedadMin'),
    				'temperaturaMax' => $this->input->post('temperaturaMax'),
    				'temperaturaMin' => $this->input->post('temperaturaMin'),
    				'descripcionCuidados' => $this->input->post('descripcionCuidados'),
    				'descripcionSustrato' => $this->input->post('descripcionSustrato'),
                );
                
                $especie_id = $this->Especies_model->add_especie($params);
                redirect('user/especies_pla/index');
            }
            else
            {            
                $this->template->user_render('public/especies/crear', $this->data);
            }
        }
    }  

    /*
     * Editing a especie
     */
    function editar($idEspecie)
    {          
        if ( ! $this->ion_auth->logged_in())
        {
            redirect('auth/login', 'refresh');
        }
        else
        {
                // check if the especie exists before trying to edit it
                $this->data['especie'] = $this->Especies_model->get_especie($idEspecie);
                
                if(isset( $this->data['especie']['idEspecie']))
                {
                    $this->load->library('form_validation');

        			$this->form_validation->set_rules('nombreEspecie','NombreEspecie','required|max_length[50]|min_length[4]');
        			$this->form_validation->set_rules('nombreCientificoEspecie','NombreCientificoEspecie','required|max_length[50]|min_length[4]');
        			$this->form_validation->set_rules('descripcionCuidados','DescripcionCuidados','max_length[255]|required|min_length[4]');
        			$this->form_validation->set_rules('luzMax','LuzMax','required|is_natural');
        			$this->form_validation->set_rules('luzMin','LuzMin','required|is_natural');
        			$this->form_validation->set_rules('humedadMax','HumedadMax','required|is_natural');
        			$this->form_validation->set_rules('humedadMin','HumedadMin','required|is_natural');
        			$this->form_validation->set_rules('temperaturaMax','TemperaturaMax','required|is_natural');
        			$this->form_validation->set_rules('temperaturaMin','TemperaturaMin','is_natural|required');
        			$this->form_validation->set_rules('descripcionSustrato','DescripcionSustrato','max_length[255]');
        		
        			if($this->form_validation->run())     
                    {   
                        $params = array(
        					'nombreEspecie' => $this->input->post('nombreEspecie'),
        					'nombreCientificoEspecie' => $this->input->post('nombreCientificoEspecie'),
        					'luzMax' => $this->input->post('luzMax'),
        					'luzMin' => $this->input->post('luzMin'),
        					'humedadMax' => $this->input->post('humedadMax'),
        					'humedadMin' => $this->input->post('humedadMin'),
        					'temperaturaMax' => $this->input->post('temperaturaMax'),
        					'temperaturaMin' => $this->input->post('temperaturaMin'),
        					'descripcionCuidados' => $this->input->post('descripcionCuidados'),
        					'descripcionSustrato' => $this->input->post('descripcionSustrato'),
                        );

                        $this->Especies_model->update_especie($idEspecie,$params);            
                        redirect('user/especies_pla/index');
                    }
                    else
                    {
                        $this->template->user_render('public/especies/editar', $this->data);
                    }
                }
                else
                    show_error('La especie que está tratando de modificar no existe.');
        }
    } 

    /**
     * Desactiva la especie, para que esta no pueda utilizarse utilizarse en cualquier otro modulo.
     * Ej.- 'Ya no se trabaja con dicha planta'
     * @param  [type] $idEspecie 
     * @return [type]           [description]
     * @author SAKZEDMK
     */
    function borrado_logico ($idEspecie)
    {
        $this->Especies_model->desactivar_especieNueva($idEspecie);
        redirect('user/especies_pla/index');
    }

    /**
     * Activa la especie, para que pueda utilizarse en cualquier otro modulo.
     * @param  [type] $idEspecie [description]
     * @return [type]           [description]
     * @author SAKZEDMK
     */
    function activado_logico($idEspecie)
    {
        $this->Especies_model->activar_especie($idEspecie);
        redirect('user/especies_pla/index');
    }    
}