<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Tareas_pla extends Public_controller{
    function __construct()
    {
        parent::__construct();
        /* CARGA LA BASE DE DATOS O MODELO*/
                if (!$this->ion_auth->logged_in() )
        {
          redirect('auth/login', 'refresh');
        }
        else
        {
        $this->data['user_login']  = $this->prefs_model->user_info_login($this->ion_auth->user()->row()->id);
        }
        $this->load->model('common/Tareas_model');
    }

    /*
     * Listing of tareas
     */
    function index()
    {       if ( ! $this->ion_auth->logged_in())
            {
                redirect('auth/login', 'refresh');
            }
            else
            {
                $this->data['tarea'] = $this->Tareas_model->listar_tareas();
                /* Load Template */
                $this->template->user_render('public/tareas/index', $this->data);

            }
    }
   /*
     AGREGAR CARGAR TAREA A BD
     */
    function add($idUmbraculo)
    {
                $this->load->library('form_validation');

                $this->form_validation->set_rules('idTipoTarea','IdTipoTarea','required');
                $this->form_validation->set_rules('fechaCreacion','FechaCreacion','required');
                $this->form_validation->set_rules('fechaAtencion','FechaAtencion');
                $this->form_validation->set_rules('fechaComienzo','FechaComienzo');
                $this->form_validation->set_rules('observacionEspecialista','ObservacionEspecialista','max_length[50]');

                if($this->form_validation->run())
                {
                    $params = array(
                        'idTipoTarea' => $this->input->post('idTipoTarea'),
                        'idEstado' => $this->input->post('idEstado'),
                        'idUserAtencion' => $this->input->post('idUserAtencion'),
                        'idUserCreador' => $this->input->post('idUserCreador'),
                        'idPlanta' => $this->input->post('idPlanta'),
                        'idUmbraculo' => $this->input->post('idUmbraculo'),
                        'fechaCreacion' => $this->input->post('fechaCreacion'),
                        'fechaAtencion' => $this->input->post('fechaAtencion'),
                        'fechaComienzo' => $this->input->post('fechaComienzo'),
                        'horaComienzo' => $this->input->post('horaComienzo'),
                        'observacionEspecialista' => $this->input->post('observacionEspecialista'),
                    );
                    if ($this->Tareas_model->comprobar_existencia_tarea( $this->input->post('idUmbraculo'),$this->input->post('fechaComienzo'), $this->input->post('idPlanta'),$this->input->post('idTipoTarea')))
                    {
                      $tareas_id = $this->Tareas_model->add_tareas($params);
                      redirect('user/umbraculos_pla/ver/'.$this->input->post('idUmbraculo'));
                    }
                    else{
                      echo "error";
                      redirect('user/umbraculos_pla/ver/'.$this->input->post('idUmbraculo'));
                    }
                }
                else
                {
                    /* Data */
                    $idUmbraculo = (int) $idUmbraculo;
                    $this->data['id'] = $idUmbraculo;

                    /*CARGA LA INFORMACION DE LOS TIPOS DE TAREA REGISTRADAS EN EL SISTEMA*/
                    $this->load->model('admin/Tipotareas_model');
                    $this->data['tipotarea'] = $this->Tipotareas_model->get_all_tipotarea();

                    /*CARGA LA INFORMACION DEL UMBRACULO PARA HACER LAS COMPRACIONES NECESARIAS*/
                    $this->load->model('common/Umbraculos_model');
                    $this->data['info_umbraculo'] = $this->Umbraculos_model->get_umbraculos($idUmbraculo);

                    /*CARGA EL PRIMER ESTADO 'No inciada' POR DEFECTO, YA QUE SE ESTÁ CREANDO RECIEN*/
                    $this->load->model('common/Estado_tarea_model');
                    $this->data['estadoDefecto'] = $this->Estado_tarea_model->get_estado_tarea(1);
                    /*CARGA LAS PLANTAS PRESENTES DENTRO DEL UMBRACULO SOBRE EL CUAL SE ESTÁ CREANDO LA TAREA*/
                    $this->load->model('common/Umbraculoplantas_model');
                    $this->data['umbraculo_plantas'] = $this->Umbraculoplantas_model->ver_plantas_umbraculo($idUmbraculo);
                    /* CARGA LA PANTALLA PARA AÑADIR UNA NUEVA TAREA*/
                    $this->template->user_render('public/umbraculos/tareas_umbraculos/add', $this->data);
                }
    }

    /**
     AGREGAR TAREA DENTRO DE UMBRACULO
     */
    function agregarTarea($idUmbraculo)
    {       if ( ! $this->ion_auth->logged_in())
            {
                redirect('auth/login', 'refresh');
            }
            else
            {
                /* CARGA LA INFORMACION DE LAS PLANTAS DEL UMBRACULO DONDE SE QUIERE CREAR LA TAREA*/
                    /* Data */
                    $idUmbraculo = (int) $idUmbraculo;
                    $this->data['id'] = $idUmbraculo;

                    /*CARGA LA INFORMACION DE LOS TIPOS DE TAREA REGISTRADAS EN EL SISTEMA*/
                    $this->load->model('admin/Tipotareas_model');
                    $this->data['tipotarea'] = $this->Tipotareas_model->get_all_tipotarea();

                    /*CARGA LA INFORMACION DEL UMBRACULO PARA HACER LAS COMPRACIONES NECESARIAS*/
                    $this->load->model('common/Umbraculos_model');
                    $this->data['info_umbraculo'] = $this->Umbraculos_model->get_umbraculos($idUmbraculo);

                    /*CARGA EL PRIMER ESTADO 'No inciada' POR DEFECTO, YA QUE SE ESTÁ CREANDO RECIEN*/
                    $this->load->model('common/Estado_tarea_model');
                    $this->data['estadoDefecto'] = $this->Estado_tarea_model->get_estado_tarea(1);
                    /*CARGA LAS PLANTAS PRESENTES DENTRO DEL UMBRACULO SOBRE EL CUAL SE ESTÁ CREANDO LA TAREA*/
                    $this->load->model('common/Umbraculoplantas_model');
                    $this->data['umbraculo_plantas'] = $this->Umbraculoplantas_model->ver_plantas_umbraculo($idUmbraculo);

                    /* CARGA LA PANTALLA PARA AÑADIR UNA NUEVA TAREA*/
                    $this->template->user_render('public/umbraculos/tareas_umbraculos/add', $this->data);
            }
    }

    function selecciona_umbraculo ()
    {
        if ( ! $this->ion_auth->logged_in())
            {
                redirect('auth/login', 'refresh');
            }
            else
            {
                $this->load->model('common/Umbraculos_model');
                $this->data['all_umbraculo'] = $this->Umbraculos_model->get_all_umbraculos();

                $this->template->user_render('public/tareas/elegir', $this->data);
            }

    }

    function ver_detalles($idTarea)
    {
        if ( ! $this->ion_auth->logged_in())
            {
                redirect('auth/login', 'refresh');
            }
            else
            {
                $this->data['insumos_tarea'] = $this->Tareas_model->insumos_tarea($idTarea);
                $this->data['tarea'] = $this->Tareas_model->ver_detalles_tarea($idTarea);
                $this->template->user_render('public/umbraculos/tareas_umbraculos/detalles', $this->data);
            }
    }
    /* borrado logico*/

      /**
       * DESACTIVA UN tarea, PARA SU UTILIZACIÓN... PERO SI YA ESTÁ UTILIZADO EN ALGÚN tarea, SE MUESTRA SU INFORMACIÓN
       * @param  [type] $idTarea COMO ÚNICO PARAMETRO DE ENTRADA
       * @return [type]           [description]
       * @author SAKZEDMK
       */
      function borrado_logico($idTarea)
      {
        $this->Tareas_model->desactivar_tarea($idTarea);
        redirect('user/tareas_pla/index');
      }

      /**
       * DESACTIVA UN tarea, PARA SU UTILIZACIÓN... PERO SI YA ESTÁ UTILIZADO EN ALGÚN tarea, SE MUESTRA SU INFORMACIÓN
       * @param  [type] $idTarea COMO ÚNICO PARAMETRO DE ENTRADA
       * @return [type]           [description]
       * @author SAKZEDMK
       */
      function activado_logico($idTarea)
      {
        $this->Tareas_model->activar_tarea($idTarea);
        redirect('user/tareas_pla/index');
      }

}
