<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Especies extends Admin_Controller{
    function __construct()
    {
        parent::__construct();
        /* Load :: Common */
        $this->lang->load('admin/especies');
        /* Title Page :: Common */
        $this->page_title->push(lang('menu_especies'));
        $this->data['pagetitle'] = $this->page_title->show();
        /* CARGA LA BASE DE DATOS O MODELO*/
        $this->load->model('common/Especies_model');

    }


    /*
     INDEX, LISTA LAS ESPECIES
     */
        public function index()
        {
            if ( ! $this->ion_auth->logged_in() OR ! $this->ion_auth->is_admin())
            {
                redirect('auth/login', 'refresh');
            }
            else
            {
                /* Breadcrumbs */
                $this->data['breadcrumb'] = $this->breadcrumbs->show();
                /* CARGO EL LISTADO DE UMBRACULOS*/

                $this->data['especies'] = $this->Especies_model->get_all_especies();


                /* Load Template */
                $this->template->admin_render('admin/especies/index', $this->data);
            }
        }

    /*
     CREAR UNA NUEVA ESPECIE
     */
    function crear()
    {   
        if ( ! $this->ion_auth->logged_in() OR ! $this->ion_auth->is_admin())
        {
            redirect('auth/login', 'refresh');
        }
        else
        {

            /* Breadcrumbs */
            $this->data['breadcrumb'] = $this->breadcrumbs->show();
            $this->load->library('form_validation');

    		$this->form_validation->set_rules('nombreEspecie','NombreEspecie','required|max_length[50]|min_length[4]');
    		$this->form_validation->set_rules('nombreCientificoEspecie','NombreCientificoEspecie','required|max_length[50]|min_length[4]');
    		$this->form_validation->set_rules('descripcionCuidados','DescripcionCuidados','max_length[255]|required|min_length[4]');
    		$this->form_validation->set_rules('luzMax','LuzMax','required|is_natural');
    		$this->form_validation->set_rules('luzMin','LuzMin','required|is_natural');
    		$this->form_validation->set_rules('humedadMax','HumedadMax','required|is_natural');
    		$this->form_validation->set_rules('humedadMin','HumedadMin','required|is_natural');
    		$this->form_validation->set_rules('temperaturaMax','TemperaturaMax','required|is_natural');
    		$this->form_validation->set_rules('temperaturaMin','TemperaturaMin','is_natural|required');
    		$this->form_validation->set_rules('descripcionSustrato','DescripcionSustrato','max_length[255]');
    		
    		if($this->form_validation->run())     
            {   
                $params = array(
    				'nombreEspecie' => $this->input->post('nombreEspecie'),
    				'nombreCientificoEspecie' => $this->input->post('nombreCientificoEspecie'),
    				'luzMax' => $this->input->post('luzMax'),
    				'luzMin' => $this->input->post('luzMin'),
    				'humedadMax' => $this->input->post('humedadMax'),
    				'humedadMin' => $this->input->post('humedadMin'),
    				'temperaturaMax' => $this->input->post('temperaturaMax'),
    				'temperaturaMin' => $this->input->post('temperaturaMin'),
    				'descripcionCuidados' => $this->input->post('descripcionCuidados'),
    				'descripcionSustrato' => $this->input->post('descripcionSustrato'),
                );
                
                $especie_id = $this->Especies_model->add_especie($params);
                redirect('common/especies/index');
            }
            else
            {            
                $this->template->admin_render('admin/especies/crear', $this->data);
            }
        }
    }  

    /*
     * Editing a especie
     */
    function editar($idEspecie)
    {          
        if ( ! $this->ion_auth->logged_in() OR ! $this->ion_auth->is_admin())
        {
            redirect('auth/login', 'refresh');
        }
        else
        {
                /* Breadcrumbs */
                $this->data['breadcrumb'] = $this->breadcrumbs->show(); 
                // check if the especie exists before trying to edit it
                $this->data['especie'] = $this->Especies_model->get_especie($idEspecie);
                
                if(isset( $this->data['especie']['idEspecie']))
                {
                    $this->load->library('form_validation');

        			$this->form_validation->set_rules('nombreEspecie','NombreEspecie','required|max_length[50]|min_length[4]');
        			$this->form_validation->set_rules('nombreCientificoEspecie','NombreCientificoEspecie','required|max_length[50]|min_length[4]');
        			$this->form_validation->set_rules('descripcionCuidados','DescripcionCuidados','max_length[255]|required|min_length[4]');
        			$this->form_validation->set_rules('luzMax','LuzMax','required|is_natural');
        			$this->form_validation->set_rules('luzMin','LuzMin','required|is_natural');
        			$this->form_validation->set_rules('humedadMax','HumedadMax','required|is_natural');
        			$this->form_validation->set_rules('humedadMin','HumedadMin','required|is_natural');
        			$this->form_validation->set_rules('temperaturaMax','TemperaturaMax','required|is_natural');
        			$this->form_validation->set_rules('temperaturaMin','TemperaturaMin','is_natural|required');
        			$this->form_validation->set_rules('descripcionSustrato','DescripcionSustrato','max_length[255]');
        		
        			if($this->form_validation->run())     
                    {   
                        $params = array(
        					'nombreEspecie' => $this->input->post('nombreEspecie'),
        					'nombreCientificoEspecie' => $this->input->post('nombreCientificoEspecie'),
        					'luzMax' => $this->input->post('luzMax'),
        					'luzMin' => $this->input->post('luzMin'),
        					'humedadMax' => $this->input->post('humedadMax'),
        					'humedadMin' => $this->input->post('humedadMin'),
        					'temperaturaMax' => $this->input->post('temperaturaMax'),
        					'temperaturaMin' => $this->input->post('temperaturaMin'),
        					'descripcionCuidados' => $this->input->post('descripcionCuidados'),
        					'descripcionSustrato' => $this->input->post('descripcionSustrato'),
                        );

                        $this->Especies_model->update_especie($idEspecie,$params);            
                        redirect('common/especies/index');
                    }
                    else
                    {
                        $this->template->admin_render('admin/especies/editar', $this->data);
                    }
                }
                else
                    show_error('La especie que está tratando de modificar no existe.');
        }
    } 

    /*
     * Deleting especie
     */
/*    function remove($idEspecie)
    {
        $especie = $this->Especies_model->get_especie($idEspecie);

        // check if the especie exists before trying to delete it
        if(isset($especie['idEspecie']))
        {
            $this->Especies_model->delete_especie($idEspecie);
            redirect('especies/index');
        }
        else
            show_error('The especie you are trying to delete does not exist.');
    }*/
    
}