<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Plantas extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Plantas_model');
    } 

    /*
     * Listing of plantas
     */
    function index()
    {
        $data['plantas'] = $this->Plantas_model->get_all_plantas();
        
        $data['_view'] = 'plantas/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new planta
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('unidadEspacioPlanta_m2','UnidadEspacioPlanta M2','required|is_natural');
		$this->form_validation->set_rules('descripcionPlanta','DescripcionPlanta','required|max_length[255]|min_length[5]');
		$this->form_validation->set_rules('nombreCientificoPlanta','NombreCientificoPlanta','required|max_length[50]|min_length[4]');
		$this->form_validation->set_rules('nombrePlanta','NombrePlanta','required|max_length[50]|min_length[4]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'idEspecie' => $this->input->post('idEspecie'),
				'unidadEspacioPlanta_m2' => $this->input->post('unidadEspacioPlanta_m2'),
				'descripcionPlanta' => $this->input->post('descripcionPlanta'),
				'nombreCientificoPlanta' => $this->input->post('nombreCientificoPlanta'),
				'nombrePlanta' => $this->input->post('nombrePlanta'),
            );
            
            $planta_id = $this->Plantas_model->add_planta($params);
            redirect('plantas/index');
        }
        else
        {
			$this->load->model('Especies_model');
			$data['all_especies'] = $this->Especies_model->get_all_especies();
            
            $data['_view'] = 'plantas/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a planta
     */
    function edit($idPlanta)
    {   
        // check if the planta exists before trying to edit it
        $data['planta'] = $this->Plantas_model->get_planta($idPlanta);
        
        if(isset($data['planta']['idPlanta']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('unidadEspacioPlanta_m2','UnidadEspacioPlanta M2','required|is_natural');
			$this->form_validation->set_rules('descripcionPlanta','DescripcionPlanta','required|max_length[255]|min_length[5]');
			$this->form_validation->set_rules('nombreCientificoPlanta','NombreCientificoPlanta','required|max_length[50]|min_length[4]');
			$this->form_validation->set_rules('nombrePlanta','NombrePlanta','required|max_length[50]|min_length[4]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'idEspecie' => $this->input->post('idEspecie'),
					'unidadEspacioPlanta_m2' => $this->input->post('unidadEspacioPlanta_m2'),
					'descripcionPlanta' => $this->input->post('descripcionPlanta'),
					'nombreCientificoPlanta' => $this->input->post('nombreCientificoPlanta'),
					'nombrePlanta' => $this->input->post('nombrePlanta'),
                );

                $this->Plantas_model->update_planta($idPlanta,$params);            
                redirect('plantas/index');
            }
            else
            {
				$this->load->model('Especies_model');
				$data['all_especies'] = $this->Especies_model->get_all_especies();

                $data['_view'] = 'plantas/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The planta you are trying to edit does not exist.');
    } 

    /*
     * Deleting planta
     */
    function remove($idPlanta)
    {
        $planta = $this->Plantas_model->get_planta($idPlanta);

        // check if the planta exists before trying to delete it
        if(isset($planta['idPlanta']))
        {
            $this->Plantas_model->delete_planta($idPlanta);
            redirect('plantas/index');
        }
        else
            show_error('The planta you are trying to delete does not exist.');
    }
    
}