<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */
defined('BASEPATH') OR exit('No direct script access allowed');
class Tipotarea extends Admin_Controller{
    function __construct()
    {
        parent::__construct();

        $this->lang->load('admin/tipoTareas_lang');


            $this->page_title->push(lang('menu'));
            $this->data['pagetitle'] = $this->page_title->show();


        /*carga del modelo*/
$this->load->model('common/Tipotarea_model');
        /* Load :: Common */


    }

    /*
     * Listing of tipotarea
     */
    function index()
    {
        if ( ! $this->ion_auth->logged_in() OR ! $this->ion_auth->is_admin())
        {
            redirect('auth/login', 'refresh');
        }
        else
        {
            /* Breadcrumbs */
            $this->data['breadcrumb'] = $this->breadcrumbs->show();
            /* CARGO EL LISTADO DE UMBRACULOS*/



            $this->data['tipotarea'] = $this->Tipotarea_model->get_all_tipotarea();







            /* Load Template */
            $this->template->admin_render('admin/tipoTareas/index', $this->data);
        }
    }


    /*
     * Adding a new tipotarea
     */
     function add()
     {
         if ( ! $this->ion_auth->logged_in() OR ! $this->ion_auth->is_admin())
         {
             redirect('auth/login', 'refresh');
         }
         else
         {

             /* Breadcrumbs */
             $this->data['breadcrumb'] = $this->breadcrumbs->show();

             $this->load->library('form_validation');

             /*$this->form_validation->set_rules('idTipoTarea','IdTipoTarea','required|max_length[50]|min_length[5]');*/
             $this->form_validation->set_rules('nombreTipoTarea','NombreTipoTarea','required|max_length[255]|min_length[5]');
             $this->form_validation->set_rules('descripcionTarea','DescripcionTarea','required|max_length[99]');


             if($this->form_validation->run())
             {
                 $params = array(
                     /*'idTipoTarea' => $this->input->post('idTipoTarea'),*/
                     'nombreTipoTarea' => $this->input->post('nombreTipoTarea'),
                     'descripcionTarea' => $this->input->post('descripcionTarea'),

                 );

                 $id_tipotarea = $this->Tipotarea_model->add_tipotarea($params); /*fijate aca que capaz por eso no carga*/
                 redirect('common/tipotarea/index');/*tipoTarea*/
             }
             else
             {

                 $this->template->admin_render('admin/tipotareas/add', $this->data);
             }
         }
     }

    /*function addes()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombreTipoTarea','NombreTipoTarea','required|max_length[50]');
		$this->form_validation->set_rules('descripcionTarea','DescripcionTarea','required|max_length[255]');

		if($this->form_validation->run())
        {
            $params = array(
				'nombreTipoTarea' => $this->input->post('nombreTipoTarea'),
				'descripcionTarea' => $this->input->post('descripcionTarea'),
            );

            $tipotarea_id = $this->Tipotarea_model->add_tipotarea($params);
            redirect('common/tipotarea/index');
        }
        else
        {
            $data['_view'] = 'tipotarea/add';
            $this->load->view('admin/tipotarea/index',$data);
        }
    }

    /*
     * Editing a tipotarea
     */
    function edit($idTipoTarea)
    {
        // check if the tipotarea exists before trying to edit it
        $data['tipotarea'] = $this->Tipotarea_model->get_tipotarea($idTipoTarea);

        if(isset($data['tipotarea']['idTipoTarea']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombreTipoTarea','NombreTipoTarea','required|max_length[50]');
			$this->form_validation->set_rules('descripcionTarea','DescripcionTarea','required|max_length[255]');

			if($this->form_validation->run())
            {
                $params = array(
					'nombreTipoTarea' => $this->input->post('nombreTipoTarea'),
					'descripcionTarea' => $this->input->post('descripcionTarea'),
                );

                $this->Tipotarea_model->update_tipotarea($idTipoTarea,$params);
                redirect('tipotarea/index');
            }
            else
            {
                $data['_view'] = 'tipotarea/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipotarea you are trying to edit does not exist.');
    }

    /*
     * Deleting tipotarea
     */
    function remove($idTipoTarea)
    {
        $tipotarea = $this->Tipotarea_model->get_tipotarea($idTipoTarea);

        // check if the tipotarea exists before trying to delete it
        if(isset($tipotarea['idTipoTarea']))
        {
            $this->Tipotarea_model->delete_tipotarea($idTipoTarea);
            redirect('common/tipotarea/index');
        }
        else
            show_error('El tipo de tarea que queres borrar no existe.');
    }

}
