<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Tipotarea extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tipotarea_model');
    }

    /*
     * Listing of tipotarea
     */
    function index()
    {
        $data['tipotarea'] = $this->Tipotarea_model->get_all_tipotarea();

        $data['_view'] = 'tipotarea/index';
        $this->load->view('admin/tipotarea/index',$data);
    }

    /*
     * Adding a new tipotarea
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombreTipoTarea','NombreTipoTarea','required|max_length[50]');
		$this->form_validation->set_rules('descripcionTarea','DescripcionTarea','required|max_length[255]');

		if($this->form_validation->run())
        {
            $params = array(
				'nombreTipoTarea' => $this->input->post('nombreTipoTarea'),
				'descripcionTarea' => $this->input->post('descripcionTarea'),
            );

            $tipotarea_id = $this->Tipotarea_model->add_tipotarea($params);
            redirect('common/tipotarea/index');
        }
        else
        {
            $data['_view'] = 'tipotarea/add';
            $this->load->view('admin/tipotarea/index',$data);
        }
    }

    /*
     * Editing a tipotarea
     */
    function edit($idTipoTarea)
    {
        // check if the tipotarea exists before trying to edit it
        $data['tipotarea'] = $this->Tipotarea_model->get_tipotarea($idTipoTarea);

        if(isset($data['tipotarea']['idTipoTarea']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombreTipoTarea','NombreTipoTarea','required|max_length[50]');
			$this->form_validation->set_rules('descripcionTarea','DescripcionTarea','required|max_length[255]');

			if($this->form_validation->run())
            {
                $params = array(
					'nombreTipoTarea' => $this->input->post('nombreTipoTarea'),
					'descripcionTarea' => $this->input->post('descripcionTarea'),
                );

                $this->Tipotarea_model->update_tipotarea($idTipoTarea,$params);
                redirect('tipotarea/index');
            }
            else
            {
                $data['_view'] = 'tipotarea/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tipotarea you are trying to edit does not exist.');
    }

    /*
     * Deleting tipotarea
     */
    function remove($idTipoTarea)
    {
        $tipotarea = $this->Tipotarea_model->get_tipotarea($idTipoTarea);

        // check if the tipotarea exists before trying to delete it
        if(isset($tipotarea['idTipoTarea']))
        {
            $this->Tipotarea_model->delete_tipotarea($idTipoTarea);
            redirect('tipotarea/index');
        }
        else
            show_error('The tipotarea you are trying to delete does not exist.');
    }

}
