<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Umbraculo_plantas extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        /* Title Page :: Common */
       // $this->page_title->push(lang('menu_plantas'));
        //$this->data['pagetitle'] = $this->page_title->show();
        /* CARGA LA BASE DE DATOS O MODELO*/
        $this->load->model('common/Umbraculoplantas_model');
    } 

    /*
    VER PLANTAS DENTRO DEL UMBRACULO
     */
    function index()
    {
        if ( ! $this->ion_auth->logged_in() OR ! $this->ion_auth->is_admin())
        {
                redirect('auth/login', 'refresh');
        }
        else
        {
            /* Breadcrumbs */
            $this->data['breadcrumb'] = $this->breadcrumbs->show();
            $this->data['umbraculo_plantas'] = $this->Umbraculoplantas_model->get_all_umbraculo_plantas();
            /* CARGAR INFORMARCION */
            $this->load->view('admin/umbraculos/umbraculos_plantas/index',$this->data);
        }
        
    }

    /*
     AGREGAR UNA NUEVA PLANTA AL UMBRACULO
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('idPlanta','IdPlanta','required');
		$this->form_validation->set_rules('cantidad','Cantidad','required');
        $this->form_validation->set_rules('idUmbraculo','idUmbraculo','required');		
		if($this->form_validation->run())     
        {   
            $params = array(
                'idUmbraculo' => $this->input->post('idUmbraculo'),
				'idPlanta' => $this->input->post('idPlanta'),
				'cantidad' => $this->input->post('cantidad'),
            );
            
            $umbraculo_plantas_id = $this->Umbraculoplantas_model->add_umbraculo_plantas($params);
            redirect('common/umbraculos/index');
        }
        else
        {
            /* Breadcrumbs */
            //$this->data['breadcrumb'] = $this->breadcrumbs->show();

                        /* Load Template */
            $this->template->admin_render('admin/umbraculos/umbraculos_plantas/add', $this->data);
        }
    } 

    /*
     RETIRAR UNA PLANTA DEL UMBRACULO
     */
    function remove($idUmbraculo,$idPlanta)
    {
        $umbraculo_plantas = $this->Umbraculoplantas_model->get_umbraculo_plantas($idUmbraculo);

        // check if the umbraculo_plantas exists before trying to delete it
        if(isset($umbraculo_plantas['idUmbraculo']))
        {
            $this->Umbraculoplantas_model->retirar_planta_umbraculo($idUmbraculo,$idPlanta);
            //redirect('umbraculo_plantas/index');
            redirect('common/umbraculos/verPlantas/'.$this->input->post('idUmbraculo'));
        }
        else
            show_error('Usted está intentado retirar una planta, no registrada, dentro de este umbráculo.');
    }
    
}