<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Umbraculos_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get umbraculo by id
     */
    function get_umbraculo($id)
    {
        return $this->db->get_where('umbraculo',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all umbraculo
     */
    function get_all_umbraculo()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('umbraculo')->result_array();
    }
        
    /*
     * function to add new umbraculo
     */
    function add_umbraculo($params)
    {
        $this->db->insert('umbraculo',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update umbraculo
     */
    function update_umbraculo($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('umbraculo',$params);
    }
    
    /*
     * function to delete umbraculo
     */
    function delete_umbraculo($id)
    {
        return $this->db->delete('umbraculo',array('id'=>$id));
    }
}
