<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Especies_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get especie by idEspecie
     */
    function get_especie($idEspecie)
    {
        return $this->db->get_where('especie',array('idEspecie'=>$idEspecie))->row_array();
    }
        
    /*
     * Get all especies
     */
    function get_all_especies()
    {
        $this->db->order_by('idEspecie', 'desc');
        return $this->db->get('especie')->result_array();
    }
        
    /*
     * function to add new especie
     */
    function add_especie($params)
    {
        $this->db->insert('especie',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update especie
     */
    function update_especie($idEspecie,$params)
    {
        $this->db->where('idEspecie',$idEspecie);
        return $this->db->update('especie',$params);
    }
    
    /*
     * function to delete especie
     */
    function delete_especie($idEspecie)
    {
        return $this->db->delete('especie',array('idEspecie'=>$idEspecie));
    }

    /**
     * Desactiva una especie, para que ya no pueda ser utilizada, por 'x' motivo
     * @param  [type] $idInsumo [description]
     * @return [type]           [description]
     */
    function desactivar_especie($idEspecie)
      {
        $query="UPDATE `especie` SET `active`=0 WHERE idEspecie=".$idEspecie;
        $this->db->query($query);
      }

    /**
    * ACTIVAR UN INSUMO QUE NO ESTÉ SIENDO UTILIZADO.
    */
        function activar_especie($idEspecie)
        {
          $query="UPDATE `especie` SET `active`=1 WHERE idEspecie=".$idEspecie;
          $this->db->query($query);
        }
}