<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Insumos_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get insumo by idInsumo
     */
    function get_insumo($idInsumo)
    {
        return $this->db->get_where('insumo',array('idInsumo'=>$idInsumo))->row_array();
    }

    /*
     * Get all insumo
     */
    function get_all_insumo()
    {
        $this->db->order_by('idInsumo', 'asc');
        return $this->db->get('insumo')->result_array();
    }

    /*
     * function to add new insumo
     */
    function add_insumo($params)
    {
        $this->db->insert('insumo',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update insumo
     */
    function update_insumo($idInsumo,$params)
    {
        $this->db->where('idInsumo',$idInsumo);
        return $this->db->update('insumo',$params);
    }

    function update_stock_insumo($idInsumo,$params)
    {
        $this->db->where('idInsumo',$idInsumo);
        return $this->db->update('insumo',$params);

    }

    /*
     * function to delete insumo
     */
    function delete_insumo($idInsumo)
    {
        return $this->db->delete('insumo',array('idInsumo'=>$idInsumo));
    }


}
