<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Insumotarea_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get insumotarea by idInsumo
     */
    function get_insumotarea($idTarea)
    {
      $query = "SELECT * FROM `insumo/tarea` JOIN insumo ON insumo.idInsumo = `insumo/tarea`.idInsumo WHERE `insumo/tarea`.idTarea=".$idTarea;
      return $this->db->query($query)->row_array();

    }

    function get_insumotareas($params)
    {
        return $this->db->get_where('insumo/tarea',array('idTarea'=>$params))->row_array();
    }

    /*
     * Get all insumotarea
     */
    function get_all_insumotarea()
    {
        $this->db->order_by('idInsumo', 'desc');
        return $this->db->get('insumo/tarea')->result_array();
    }

    /*
     * function to add new insumotarea
     */
    function add_insumotarea($params)
    {
        $this->db->insert('insumo/tarea',$params);
        return $this->db->insert_id();
    }

    /*
     * function to update insumotarea
     */
    function update_insumotarea($idInsumo,$params)
    {
        $this->db->where('idInsumo',$idInsumo);
        return $this->db->update('insumo/tarea',$params);
    }

    /*
     * function to delete insumotarea
     */
    function delete_insumotarea($idInsumo)
    {
        return $this->db->delete('insumo/tarea',array('idInsumo'=>$idInsumo));
    }
}
