<?php
<<<<<<< HEAD
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
=======
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

>>>>>>> giuli
class Tipotarea_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
<<<<<<< HEAD
    
=======

>>>>>>> giuli
    /*
     * Get tipotarea by idTipoTarea
     */
    function get_tipotarea($idTipoTarea)
    {
        return $this->db->get_where('tipotarea',array('idTipoTarea'=>$idTipoTarea))->row_array();
    }
<<<<<<< HEAD
        
=======

>>>>>>> giuli
    /*
     * Get all tipotarea
     */
    function get_all_tipotarea()
    {
        $this->db->order_by('idTipoTarea', 'desc');
        return $this->db->get('tipotarea')->result_array();
    }
<<<<<<< HEAD
        
=======

>>>>>>> giuli
    /*
     * function to add new tipotarea
     */
    function add_tipotarea($params)
    {
        $this->db->insert('tipotarea',$params);
        return $this->db->insert_id();
    }
<<<<<<< HEAD
    
=======

>>>>>>> giuli
    /*
     * function to update tipotarea
     */
    function update_tipotarea($idTipoTarea,$params)
    {
        $this->db->where('idTipoTarea',$idTipoTarea);
        return $this->db->update('tipotarea',$params);
    }
<<<<<<< HEAD
    
=======

>>>>>>> giuli
    /*
     * function to delete tipotarea
     */
    function delete_tipotarea($idTipoTarea)
    {
        return $this->db->delete('tipotarea',array('idTipoTarea'=>$idTipoTarea));
    }
}
