<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Umbraculoplantas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get umbraculo_plantas by idUmbraculo
     */
    function get_umbraculo_plantas($idUmbraculo)
    {
        return $this->db->get_where('umbraculo/planta',array('idUmbraculo'=>$idUmbraculo))->result_array();
    }
        
    /*
     * Get all umbraculo_plantas
     */
    function get_all_umbraculo_plantas()
    {
        $this->db->order_by('idUmbraculo', 'desc');
        return $this->db->get('umbraculo/planta')->result_array();
    }
        
    /*
     * function to add new umbraculo_plantas
     */
    function add_umbraculo_plantas($params)
    {
        $this->db->insert('umbraculo/planta',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update umbraculo_plantas
     */
    function update_umbraculo_plantas($idUmbraculo,$params)
    {
        $this->db->where('idUmbraculo',$idUmbraculo);
        return $this->db->update('umbraculo/planta',$params);
    }
    
    /*
     * function to delete umbraculo_plantas
     */
    function delete_umbraculo_plantas($idUmbraculo)
    {
        return $this->db->delete('umbraculo/planta',array('idUmbraculo'=>$idUmbraculo));
    }
}