<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Umbraculoplantas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('common/plantas_model');
    }
    
    /*
     OBTENER LAS PLANTAS QUE ESTAN ALOJADAS EN UN DETERMINADO UMBRÁCULO
     */
    function get_umbraculo_plantas($idUmbraculo)
    {
        return $this->db->get_where('umbraculo/planta',array('idUmbraculo'=>$idUmbraculo))->result_array();
    }

    /*
     OBTENER LAS PLANTAS QUE ESTAN ALOJADAS EN UN DETERMINADO UMBRÁCULO
     */

     /*
     OBTENER LAS PLANTAS QUE ESTAN ALOJADAS EN UN DETERMINADO UMBRÁCULO, CON SU RESPECTIVO NOMBRE LIMITE 3
     */
    function get_umbraculo_plantas_nombre($idUmbraculo)
    {
        $query = "SELECT * FROM `umbraculo/planta` JOIN planta ON planta.idPlanta = `umbraculo/planta`.idPlanta WHERE `umbraculo/planta`.idUmbraculo=".$idUmbraculo." LIMIT 0,3";

        return $this->db->query($query)->result_array();
    }
     /*
     OBTENER TODAS LAS PLANTAS QUE ESTAN ALOJADAS EN UN DETERMINADO UMBRÁCULO, CON SU RESPECTIVO NOMBRE 
     */
        function ver_plantas_umbraculo($idUmbraculo)
    {
        $query = "SELECT * FROM `umbraculo/planta` JOIN planta ON planta.idPlanta = `umbraculo/planta`.idPlanta WHERE `umbraculo/planta`.idUmbraculo=".$idUmbraculo;

        return $this->db->query($query)->result_array();
    }


    /*
     OBTENER PLANTAS UMBRACULO
     */
    function get_all_umbraculo_plantas()
    {
        $this->db->order_by('idUmbraculo', 'desc');
        return $this->db->get('umbraculo/planta')->result_array();
    }
        
    /*
     * function to add new umbraculo_plantas
     */
    function add_umbraculo_plantas($params)
    {
        $query = "INSERT INTO `umbraculo/planta`(`idPlanta`, `cantidad`, `idUmbraculo`) VALUES (".$params['idPlanta'].",".$params['cantidad'].",".$params['idUmbraculo'].")";
        $this->db->query($query);
    }
    
    /*
     * function to update umbraculo_plantas
     */
    function update_umbraculo_plantas($idUmbraculo,$params)
    {
        $this->db->where('idUmbraculo',$idUmbraculo);
        return $this->db->update('umbraculo/planta',$params);
    }
    
    /*
     * FUNCION PARA RETIRAR UNA PLANTA DENTRO DE UN DETERMINADO UMBRACULO
     */
    function retirar_planta_umbraculo($idUmbraculo,$idPlanta)
    {
        $query="DELETE FROM `umbraculo/planta` WHERE idPlanta = ".$idPlanta." AND idUmbraculo =".$idUmbraculo;
        return $this->db->query($query);
        //return $this->db->delete('umbraculo/planta',array('idUmbraculo'=>$idUmbraculo));
    }
}